Added search results page, improved styling, converted html to MUI
texhnolyzer89/Redux-MUI-project pull request #1
Opened 2022-06-15 21:55 UTC by solidityGuy

As said in title:

- Added search results
- Improved styling
- Converted html to MUI

2022-06-16 09:56 UTC, AdrianLorenzoDev requested changes
It is looking fine! Take a look at my comments, please :)

2022-06-16 09:56 UTC, AdrianLorenzoDev commented on src/components/SearchResults.tsx
> +const API_KEY = "7574dfa3f440636c752e8baf90fd52da";
API keys shouldn't be hardcoded in code. It should be contained in ENV files

2022-06-16 09:56 UTC, AdrianLorenzoDev commented on src/components/SearchResults.tsx
> +    const[total, setTotal] = useState(10000);
Why is total set to `10000`?

2022-06-16 09:56 UTC, AdrianLorenzoDev commented on src/components/SearchResults.tsx
> +        }
Network calls should be abstracted into components to avoid repeating code

2022-06-16 09:56 UTC, AdrianLorenzoDev commented on src/components/SearchResults.tsx
> +    )
I think that you can abstract this into components, since you are using a map and there is a smaller component being used that could be reused somewhere else

2022-06-16 09:56 UTC, AdrianLorenzoDev commented on src/components/Feed.tsx
> -import { Box, Button } from '@mui/material';
`Feed` and `FeedPopular` code is very similar and therefore, there is repeated code we could abstract into reusable components

2022-06-16 11:27 UTC, tainguyenbui commented on src/components/SearchResults.tsx
> +        <Box flex={9} p={2} sx={{ display: 'flex', flexDirection: 'column', alignItems: 'center'}} >
maybe we could start applying styles in css

2022-06-16 16:55 UTC, solidityGuy commented on src/components/SearchResults.tsx
> +const API_KEY = "7574dfa3f440636c752e8baf90fd52da";
Implemented.

2022-06-16 16:56 UTC, solidityGuy commented on src/components/SearchResults.tsx
> +    const[total, setTotal] = useState(10000);
Fixed to correct number.

2022-06-16 16:56 UTC, solidityGuy commented on src/components/SearchResults.tsx
> +        }
Implemented.

2022-06-16 16:56 UTC, solidityGuy commented on src/components/SearchResults.tsx
> +    )
Implemented.

2022-06-16 16:56 UTC, solidityGuy commented on src/components/Feed.tsx
> -import { Box, Button } from '@mui/material';
Implemented.

2022-06-16 16:56 UTC, solidityGuy commented on src/components/SearchResults.tsx
> +        <Box flex={9} p={2} sx={{ display: 'flex', flexDirection: 'column', alignItems: 'center'}} >
Implemented.

2022-06-16 16:56 UTC, solidityGuy commented
Implemented changes

2022-06-17 07:07 UTC, AdrianLorenzoDev approved these changes
LGTM!

2022-06-17 07:07 UTC, AdrianLorenzoDev commented on src/components/Feed.tsx
> +    const[total, setTotal] = useState(20);
I know you removed the 10k value because of my comment, but I think that you didn't answer my question.

Why 20 or 10000? Which is the decision behind the value selected?

2022-06-17 07:07 UTC, AdrianLorenzoDev commented on src/requests.tsx
> +export async function getMovies(fetchUrl:string) {
Does the `getMovies` URL change, in terms of baseline URL? If not, I think it should be contained here to avoid having repeated code in other parts of the codebase.

Also, instead of appending the endpoints to the URL, you can create different functions to abstract the behaviour of your application. Thanks to this, your application will have more semantic and will be more reusable.

For example, this is a potential interface specification that you could use:

```typescript
type Page = number

interface MovieSearchParameters {
  query?: string
  language?: string
  region?: string
  year?: string
}

interface MoviesRepository {
   getTrendy(page: Page)
   getTopRated(page: Page)
   search(parameters: [MovieSearchParameters], page: Page)
}
```

2022-06-17 07:07 UTC, AdrianLorenzoDev commented on src/components/MovieBox.tsx
> +const MovieBox = ({id, title, name, poster, overview}: {id: number, title: string, name: string, poster: string, overview: string}) => {
This could be simpler:

```suggestion
const MovieBox = ({id: number, title: string, name: string, poster: string, overview: string}) => {
```

2022-06-17 12:27 UTC, solidityGuy commented on src/pages/Results.tsx
> +    const [query, setQuery] = useState(location.search.replace(/[?]/, "&"));
I used this mechanism because I previously tried using use useParams() and it wasn't doing the behaviour I expected.

Going this route and using the useLocation() hook would return the string ?query="xxxx", which I could manipulate by replacing the "?", creating a "&query="xxxx" string.

This string appended to the API URL would make a request which returned the desired results.

2022-06-17 12:28 UTC, solidityGuy commented on src/components/Feed.tsx
> +    const[total, setTotal] = useState(20);
Oh sorry about that, I didn't notice!

For the variable value I just put any value before the actual value is rended through useEffect(). So 10000 would be a similar value to the total of Movies, and 20 is one page of movies, so that if it fails there is at least one page.

10000 would probably be a better value as a temporary variable.

2022-06-17 19:46 UTC, solidityGuy commented on src/components/MovieBox.tsx
> +const MovieBox = ({id, title, name, poster, overview}: {id: number, title: string, name: string, poster: string, overview: string}) => {
I tried this locally, but for some reason it did not work...

2022-06-17 19:46 UTC, solidityGuy commented on src/requests.tsx
> +export async function getMovies(fetchUrl:string) {
No, the baseURL does not change.

I've restructured the networking section in a similar way to the one you proposed.

2024-05-22 14:29 UTC, closed without merging